export docs
phero-hq/website pull request #4
Opened 2022-11-07 11:21 UTC by kamilafsar

Adds docs for the export command.

2022-11-09 07:45 UTC, Jpunt requested changes
Nice 👍 Some notes though 😉

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/gcloud-functions.md
> +When you export you server, Phero compiles an optimized server for you to deploy.
```suggestion
In order to deploy your Phero server, there's one last step: making an export. When you export your server, Phero compiles an optimised bundle for you to deploy.
```

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/gcloud-functions.md
> +First navigate to your server dir:
```suggestion
First, navigate to your server directory and install `@google-cloud/functions-framework`:
```

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/gcloud-functions.md
> +```
```suggestion
cd api
npm install @google-cloud/functions-framework
```

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/gcloud-functions.md
> +This will output an `export` directory with a directory for each `service`.
Didn't we think defining the export-directory in the command (like `npx phero server export ./export --flavor gcloud-functions`) was a bit more flexible across the different flavors? Or is that something to fix later on?

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/gcloud-functions.md
> +To deploy one of your services, run:
```suggestion
This will output an `export` directory with a directory for each `service`. To deploy one of these services, run:
```

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/gcloud-functions.md
> +Note that this example deploys a function called `helloWorldService`. You probably have named your service something else ;). Just replace `helloWorldService` with the name of your service.
```suggestion
Note that this example deploys a Google Cloud Function called `helloWorldService`. You probably have named your service something else ;). Replace `helloWorldService` with the name of your service.
```

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/gcloud-functions.md
> +You probably also want to specify your region, and more...
```suggestion
Here's the full documentation for this command: https://cloud.google.com/sdk/gcloud/reference/functions/deploy. You probably also want to specify your region, and more...
```

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/nodejs.md
> +When you export you server, Phero compiles an optimized server for you to deploy.
```suggestion
In order to deploy your Phero server, there's one last step: making an export. When you export your server, Phero compiles an optimised bundle for you to deploy.
```

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/nodejs.md
> +It does **not** use any framework like `express` or `fastify`. It compiles down to plain JavaScript which uses the built-in `http` module from NodeJS itself. This way we can guarantee there's little
```suggestion
It does **not** use any framework like `express` or `fastify`. It compiles down to plain JavaScript which uses the built-in `http` module from NodeJS itself. This way we can guarantee that there's as little overhead as possible between a request and actually calling your function.
```

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/nodejs.md
> +First navigate to your server dir:
```suggestion
First, navigate to your server directory:
```

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/nodejs.md
> +This will generate a node script for each of your services. To run one of your services:
```suggestion
This will generate a node script for each of your services in an `export` directory. To run one of these services:
```

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/nodejs.md
> +That's it! From here it should be fairly straight forward to deploy it to serveral cloud providers or anywhere you like.
```suggestion
That's it! From here you can deploy this bundle to any provider that supports NodeJS.
```

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/vercel.md
> +When you export you server, Phero compiles an optimized server for you to deploy.
```suggestion
In order to deploy your Phero server, there's one last step: making an export. When you export your server, Phero compiles an optimised bundle for you to deploy.
```

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/vercel.md
> +For now Phero compiles your services into Vercel Serverless Functions. There's no way yet to compile it into Edge functions.
```suggestion
For now, Phero compiles your services into Vercel Serverless Functions, Edge Functions are not yet supported.
```

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/vercel.md
> +First navigate to your server dir:
```suggestion
First, navigate to your server directory:
```

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/vercel.md
> +This will generate an hidden `.vercel` directory with all the code necessary to deploy.
```suggestion
This will generate a `.vercel` directory, with all the code necessary to deploy.
```

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/vercel.md
> +To deploy, please run:
```suggestion
To deploy this bundle, run:
```

2022-11-09 07:45 UTC, Jpunt commented on docs/deploying-phero/vercel.md
> +For each subsequent deploy you can repeat the steps above.
```suggestion
That's it! For each subsequent deploy you can repeat the steps above.
```

2022-11-14 14:35 UTC, kamilafsar commented on docs/deploying-phero/gcloud-functions.md
> +Note that this example deploys a function called `helloWorldService`. You probably have named your service something else ;). Just replace `helloWorldService` with the name of your service.
"just" detector activated :P

2022-11-14 14:38 UTC, kamilafsar commented on docs/deploying-phero/vercel.md
> +To deploy, please run:
hmmm bundle could be a bit misleading as we're deploying multiple functions/bundles..

2022-11-14 15:45 UTC, Jpunt commented on docs/deploying-phero/vercel.md
> +To deploy, please run:
"To deploy your server"?

2022-11-14 16:53 UTC, JasperH8g approved these changes

2022-11-14 16:54 UTC, merged